### ISSUE TITLE
Error: Using Differentiated Keys seems to throw errors

### ISSUE THREAD

**Issue by woodwardmatt** [woodwardmatt/hashgraph-tools#1]
**CONTEXT**: 
The recent update to use differentiated keys seems to be causing some issues. Needs some further R & D with Hedera devs.

**ERRORS**: 
An error minting the nft: StatusError: receipt for transaction 0.0.0@00000000000000000 contained error status INVALID_SIGNATURE

**WORKAROUND**: 
Revert to using the single account for all key types until a further update is provided.

**Comment by edufolios-matt** [comment]
Corrected with: https://github.com/woodwardmatt/hashgraph-tools/commit/4c8efac6987af9aad9482bd85418be01551fc86a

This issue was due to the keys used to sign when creating & minting transactions.
