### ISSUE TITLE
The importance of knowing what keys to set

### ISSUE THREAD

**Issue by justynspooner** [woodwardmatt/hashgraph-tools#2]
Hi Matt. This is less of a bug and more of an awareness piece. Your scripts are a great resource for getting someone up and running but it's important they know what the keys do if/when they come to mint a larger collection that they want to put out to the public.

Right now I believe you can't remove the keys once set. If someone runs the mint token script then all their keys will be set which might not be what they're after.

Having a Wipe key set for example would let them burn a token in someone else's account which might not be what they're after.

The update might just be a simple change to the Readme and also a comment in an `.env.example` file with what each key is for:
`.env.example`
```
# The supply key lets you mint new tokens under the token ID
# SUPPLY_KEY=

# The admin key lets you update the global properties of your token such as the name, symbol and the treasury account. If you want your token to be immutable then don't set this
# ADMIN_KEY=

etc
```

and then to add conditional keys only if they're set in the .env file.
```
const adminKey = process.env.ADMIN_KEY
const supplyKey = process.env.SUPPLY_KEY
if (adminKey) {
    transaction.setAdminKey(PrivateKey.fromString(adminKey))
}
if (supplyKey) {
    transaction.setSupplyKey(PrivateKey.fromString(supplyKey))
}
etc…
```

On a side note, I have added a HIP proposal to address the fact that you can't remove keys once set. I'd appreciate it if you had a moment to add any comments/feedback. Thanks!

https://github.com/hashgraph/hedera-improvement-proposal/pull/540

**Comment by justynspooner** [comment]
I definitely jumped the gun on this issue. Your `.env` file beautifully illustrates what each key does!

The only thing I would add is the fact that you can't remove them once set.

I also assume that if a key is not set in the `.env` then each line here just silently fails and doesn't add it to the transaction?
https://github.com/woodwardmatt/hashgraph-tools/blob/main/mint.js#L198

**Comment by woodwardmatt** [comment]
(Just the 2 years late on this response!) 😬

At this point only the supply key is required for minting using the script. The other keys are conditionally set if provided in the env file.
